- name: Git auto deploy
  hosts: all
  remote_user: "{{ u }}"
  # gather_facts: no
  pre_tasks:
    - name: Unlimit SSH port 22 using ufw command
      ufw:
        rule: allow
        port: ssh
      tags:
        - always
    - name: May install python
      raw: >
        test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        && test -e /usr/bin/pip || (apt -y update && apt install -y python-pip)
        && pip show docker || pip install docker
        && pip show docker-compose || pip install docker-compose
      register: output
      changed_when: output.stdout != ''
      tags:
        - always
  tasks:
    - block:
        - import_role:
            name: set-remote
          tags:
            - set-remote
      always:
        - name: Limit SSH port 22 using ufw command
          ufw:
            rule: limit
            port: ssh
          tags:
            - always

  
