- name: Git auto deploy
  hosts: staging
  remote_user: root
  gather_facts: no
  vars:
    working_tree_hub: $HOME/.agad-working-tree
    bare_git_hub: $HOME/.agad-bare-git
  pre_tasks:
    - fail:
        msg: "'repo_name' variable is required"
      when: repo_name is not defined
      tags:
        - always
    - name: Unlimit SSH port 22 using ufw command
      ufw:
        rule: allow
        port: ssh
      tags:
        - always
    - name: May install python
      raw: >
        test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        && test -e /usr/bin/pip || (apt -y update && apt install -y python-pip)
        && pip show docker || pip install docker
        && pip show docker-compose || pip install docker-compose
      register: output
      changed_when: output.stdout != ''
      tags:
        - always
  tasks:
    - name: Setup remote git auto deploy
      block:
        - name: Ensure existence of bare git repo directory
          file:
            path: "{{ bare_git_hub }}"
            state: directory
        - set_fact:
            working_target: "{{ working_tree_hub }}/{{ repo_name }}"
            repo_target: "{{ bare_git_hub }}/{{ repo_name }}.git"
            branch: "{{ branch|default('master') }}"
            hook: "{{ hook|default('') }}"
          tags:
            - set-fact
        - set_fact:
            post_receive_hook_file: "{{ repo_target }}/hooks/post-receive"
          tags:
            - set-fact
        - name: Create bare git repo
          shell: git init --bare {{ repo_target }}
        - name: Create working directory
          file:
            path: "{{ working_target }}"
            state: directory
        - name: Add default post-receive hook file
          template:
            src: ./post-receive.j2
            dest: "{{ post_receive_hook_file }}"
            mode: 0754
          when: hook == ''
          tags:
            - default_hook
        - name: Add post-receive hook file
          copy:
            src: "{{ hook }}"
            dest: "{{ post_receive_hook_file }}"
          when: hook != ''
          tags:
            - custom_hook
      always:
        - name: Limit SSH port 22 using ufw command
          ufw:
            rule: limit
            port: ssh
          tags:
            - always
